config/routes.rb
Rails.application.routes.draw do
  get "home/index"
  namespace :front do
    resources :majors
    resources :teachers
  end

  namespace :admin do
    get "/", to: "dashboards#index", as: :index
    resources :teachers
    resources :educations
    resources :majors
    resources :schools
    resources :users
  end
  devise_for :users

  get "up" => "rails/health#show", as: :rails_health_check

  root "homes#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/education.rb
class Education < ApplicationRecord
  validates :education_name, presence: { message: "学历名称必须填写" },
            uniqueness: { message: "学历已存在，请勿重复" }
end

app/models/major.rb
class Major < ApplicationRecord
  has_many :teachers
  validates :major_name, presence: true, uniqueness: true
end

app/models/school.rb
class School < ApplicationRecord
  validates :school_name, presence: true, uniqueness: true
end

app/models/teacher.rb
class Teacher < ApplicationRecord
  belongs_to :school
  belongs_to :major
  belongs_to :education
  has_one_attached :photo
end

app/models/user.rb
class User < ApplicationRecord
  attr_accessor :login

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         authentication_keys: [ :login ]

  validates :username, presence: true, uniqueness: true
  validates :phone, presence: true, uniqueness: true

  def self.find_for_database_authentication(warden_conditions)
    conditions = warden_conditions.dup
    login = conditions.delete(:login)&.downcase

    where(conditions).where(
    # ["lower(username) = :value OR lower(email) = :value", { value: login }]
    [ "lower(phone) = :value", { value: login } ]
    ).first
  end
end

app/controllers/admin/dashboards_controller.rb
class Admin::DashboardsController < ApplicationController
  before_action :authenticate_user!
  before_action :check_superuser # 确保超级用户

  def index
  end

  private

  def check_superuser
    unless current_user.is_superuser
      redirect_to new_user_session_path, alert: "你没有权限访问该页面"
    end
  end
end

app/controllers/admin/majors_controller.rb
class Admin::MajorsController < ApplicationController
  def index
    @majors = Major.all
  end

  def show
    @major = Major.find(params[:id])
  end

  def new
    @major = Major.new
  end

  def create
    @major = Major.new(majors_params)
    if @major.save
      redirect_to admin_majors_path, notice: "成功创建专业"
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @major = Major.find(params[:id])
  end

  def update
    @major = Major.find(params[:id])
    if @major.update(majors_params)
      redirect_to admin_major_path(@major), notice: "成功修改专业"
    else
      render :show, status: :unprocessable_entity
    end
  end

  def destroy
    @major = Major.find(params[:id])
    @major.destroy
    redirect_to admin_majors_path, notice: "成功删除专业"
  end

  private

  def majors_params
    params.require(:major).permit(:major_name)
  end
end

app/controllers/admin/schools_controller.rb
class Admin::SchoolsController < ApplicationController
  def index
    @schools = School.all
  end

  def show
    @school = School.find(params[:id])
  end

  def new
    @school = School.new
  end

  def create
    @school = School.new(school_params)
    if @school.save
      redirect_to admin_schools_path, notice: "添加学校 #{@school.school_name} 成功"
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @school = School.find(params[:id])
  end

  def update
    @school = School.find(params[:id])
    if @school.update(school_params)
      redirect_to admin_school_path(@school)
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @school = School.find(params[:id])
    @school.destroy
    redirect_to admin_schools_path, notice: "成功删除学校"
  end

  private

  def school_params
    params.require(:school).permit(:school_name, :address)
  end
end

app/controllers/admin/teachers_controller.rb
class Admin::TeachersController < ApplicationController
  before_action :set_teacher, only: [ :show, :edit, :update, :destroy ]

  def index
    if params[:query].present?
      q = "%#{params[:query]}%"
      @teachers = Teacher.where("name LIKE ? OR position LIKE ?", q, q)
    else
      @teachers = Teacher.all
    end
  end


  def show
  end

  def new
    @teacher = Teacher.new
  end

  def create
    @teacher = Teacher.new(teacher_params)
    if @teacher.save
      redirect_to admin_teachers_path, notice: "成功创建教师 #{@teacher.name}"
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @teacher = Teacher.find(params[:id])
  end

  def update
    if @teacher.update(teacher_params)
      redirect_to admin_teacher_path(@teacher), notice: "成功修改教师 #{@teacher.name}"
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @teacher.destroy
    redirect_to admin_teachers_path, notice: "成功删除教师 #{@teacher.name}"
  end

  private

  def set_teacher
    @teacher = Teacher.find(params[:id])
  end

  def teacher_params
    params.require(:teacher).permit(
      :name, :gender, :position, :award_certificates, :honors, :teacher_license,
      :bio, :experience, :phone, :wechat, :school_id, :major_id, :education_id, :photo,
      )
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :require_superuser
  before_action :set_user, only: [ :edit, :update, :destroy ]

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to admin_users_path, notice: "用户创建成功"
    else
      render :new
    end
  end

  def edit; end

  def update
    if @user.update(user_params)
      redirect_to admin_users_path, notice: "用户更新成功"
    else
      render :edit
    end
  end

  def destroy
    @user.destroy
    redirect_to admin_users_path, notice: "用户已删除"
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:username, :phone, :email, :password, :password_confirmation, :is_superuser)
  end

  def require_superuser
    redirect_to root_path, alert: "没有权限" unless current_user&.is_superuser?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  private

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_in, keys: [ :login ])
    # 注册时允许 username
    devise_parameter_sanitizer.permit(:sign_up, keys: [ :username, :email, :phone ])
    # 修改资料时允许 username
    devise_parameter_sanitizer.permit(:account_update, keys: [ :username, :email, :phone ])
  end
end

app/controllers/front/majors_controller.rb
class Front::MajorsController < ApplicationController
end

app/controllers/front/teachers_controller.rb
class Front::TeachersController < ApplicationController
  def index
    if params[:major_id].present?
      @major = Major.find(params[:major_id])
      @teachers = @major.teachers
    else
      @teachers = Teacher.all
    end
    render :'front/teachers/index'
  end


  def show
    @teacher = Teacher.find(params[:id])
    render :'front/teachers/show'
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def index
    @majors = Major.all
  end
end

app/helpers/admin/dashboards_helper.rb
module Admin::DashboardsHelper
end

app/helpers/admin/educations_helper.rb
module Admin::EducationsHelper
end

app/helpers/admin/majors_helper.rb
module Admin::MajorsHelper
end

app/helpers/admin/schools_helper.rb
module Admin::SchoolsHelper
end

app/helpers/admin/teachers_helper.rb
module Admin::TeachersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/front/majors_helper.rb
module Front::MajorsHelper
end

app/helpers/front/teachers_helper.rb
module Front::TeachersHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/majors/_form.html.erb
<!-- app/views/majors/_form.html.erb -->

<% if major.errors.any? %>
  <div style="color: red;">
    <h2><%= pluralize(major.errors.count, "错误") %>阻止了保存：</h2>
    <ul>
      <% major.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<%= form_with model: [:admin, @major], local: true do |f| %>
  <div>
    <%= f.label :major_name, "专业名称" %><br>
    <%= f.text_field :major_name %>
  </div>

  <div>
    <%= f.submit %>
  </div>
<% end %>

app/views/admin/majors/edit.html.erb
<!-- app/views/majors/edit.html.erb -->

<h1>编辑专业</h1>
<%= render 'shared/admin_navbar' %>

<%= render "form", major: @major %>

<%= link_to "返回列表", admin_majors_path %>

app/views/admin/majors/index.html.erb
<!-- app/views/majors/index.html.erb -->

<h1>专业列表</h1>

<%= render "shared/admin_navbar" %>

<% if notice %>
  <p style="color: green;"><%= notice %></p>
<% end %>

<table>
  <thead>
  <tr>
    <th>ID</th>
    <th>专业名称</th>
    <th>操作</th>
  </tr>
  </thead>
  <tbody>
  <% @majors.each do |major| %>
    <tr>
      <td><%= major.id %></td>
      <td><%= major.major_name %></td>
      <td style="display: flex">
        <%= link_to "查看", admin_major_path(major) %> |
        <%= link_to "编辑", edit_admin_major_path(major) %> |
        <%= button_to "删除", admin_major_path(major), style: "cursor: pointer", method: :delete, data: { turbo_confirm: "确定删除吗？" } %>
      </td>
    </tr>
  <% end %>
  </tbody>
</table>

<br>

<%= link_to "添加新专业", new_admin_major_path %>

app/views/admin/majors/new.html.erb
<!-- app/views/majors/new.html.erb -->

<h1>添加新专业</h1>
<%= render 'shared/admin_navbar' %>

<%= render "form", major: @major %>

<%= link_to "返回列表", admin_majors_path %>

app/views/admin/majors/show.html.erb
<!-- app/views/majors/show.html.erb -->

<h1>专业详情</h1>

<p>
  <strong>ID:</strong>
  <%= @major.id %>
</p>

<p>
  <strong>专业名称:</strong>
  <%= @major.major_name %>
</p>

<%= link_to "编辑", edit_admin_major_path(@major) %> |
<%= link_to "返回列表", admin_majors_path %>

app/views/admin/teachers/_form.html.erb
<% if @teacher.errors.any? %>
  <div style="color: red;">
    <ul>
      <% @teacher.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<%= form_with model: [:admin, @teacher], local: true do |f| %>
  <div>
    <%= f.label :photo, "照片" %><br>
    <%= f.file_field :photo, accept: "image/*" %>
  </div>

  <div>
    <%= f.label :name, "姓名" %><br>
    <%= f.text_field :name %>
  </div>

  <div>
    <%= f.label :gender, "性别" %><br>
    <%= f.select :gender, [%w[男 男], %w[女 女]] %>
  </div>

  <div>
    <%= f.label :position, "职务" %><br>
    <%= f.text_field :position %>
  </div>

  <div>
    <%= f.label :award_certificates, "获奖证书" %><br>
    <%= f.text_area :award_certificates %>
  </div>

  <div>
    <%= f.label :honors, "荣誉" %><br>
    <%= f.text_area :honors %>
  </div>

  <div>
    <%= f.label :teacher_license, "教师证号" %><br>
    <%= f.text_field :teacher_license %>
  </div>

  <div>
    <%= f.label :bio, "个人简介" %><br>
    <%= f.text_area :bio %>
  </div>

  <div>
    <%= f.label :experience, "工作经验" %><br>
    <%= f.text_area :experience %>
  </div>

  <div>
    <%= f.label :phone, "电话" %><br>
    <%= f.text_field :phone %>
  </div>

  <div>
    <%= f.label :wechat, "微信" %><br>
    <%= f.text_field :wechat %>
  </div>

  <div>
    <%= f.label :school_id, "学校" %><br>
    <%= f.collection_select :school_id, School.all, :id, :school_name, prompt: "请选择学校" %>
  </div>

  <div>
    <%= f.label :major_id, "专业" %><br>
    <%= f.collection_select :major_id, Major.all, :id, :major_name, prompt: "请选择专业" %>
  </div>

  <div>
    <%= f.label :education_id, "学历" %><br>
    <%= f.collection_select :education_id, Education.all, :id, :education_name, prompt: "请选择学历" %>
  </div>

  <div>
    <%= f.submit @teacher.new_record? ? "添加教师" : "更新教师" %>
  </div>
<% end %>

app/views/admin/teachers/edit.html.erb
<h1>编辑教师</h1>

<%= render "form" %>

<%= link_to "返回列表", admin_teachers_path %>

app/views/admin/teachers/index.html.erb
<h1>教师列表</h1>

<%= render "shared/admin_navbar" %>
<%= form_with url: admin_teachers_path, method: :get, local: true do |f| %>
  <%= f.label :query, "搜索教师" %>
  <%= f.text_field :query, value: params[:query] %>
  <%= f.submit "搜索" %>
<% end %>
<% if notice %>
  <p style="color: green;"><%= notice %></p>
<% end %>

<table>
  <thead>
  <tr>
    <th>ID</th>
    <th>姓名</th>
    <th>性别</th>
    <th>职务</th>
    <th>学校</th>
    <th>专业</th>
    <th>学历</th>
    <th>操作</th>
  </tr>
  </thead>
  <tbody>
  <% @teachers.each do |teacher| %>
    <tr>
      <td><%= teacher.id %></td>
      <td><%= teacher.name %></td>
      <td><%= teacher.gender %></td>
      <td><%= teacher.position %></td>
      <td><%= teacher.school.school_name if teacher.school %></td>
      <td><%= teacher.major.major_name if teacher.major %></td>
      <td><%= teacher.education.education_name if teacher.education %></td>
      <td style="display: flex;">
        <%= link_to "查看", admin_teacher_path(teacher) %> |
        <%= link_to "编辑", edit_admin_teacher_path(teacher) %> |
        <%= button_to "删除", admin_teacher_path(teacher), method: :delete, style: "cursor: pointer", data: { turbo_confirm: "确定删除吗？" } %>
      </td>
    </tr>
  <% end %>
  </tbody>
</table>

<br>

<%= link_to "添加新教师", new_admin_teacher_path %>

app/views/admin/teachers/new.html.erb
<h1>添加新教师</h1>
<%= render 'shared/admin_navbar' %>

<%= render "form" %>

<%= link_to "返回列表", admin_teachers_path %>

app/views/admin/teachers/show.html.erb
<h1>教师详情</h1>
<%= render 'shared/admin_navbar' %>

<%= render "shared/admin_navbar" %>

<% if @teacher.photo.attached? %>
  <%= image_tag @teacher.photo.variant(resize_to_fill: [150, 200]) %>
<% end %>

<p><strong>姓名:</strong> <%= @teacher.name %></p>
<p><strong>性别:</strong> <%= @teacher.gender %></p>
<p><strong>职务:</strong> <%= @teacher.position %></p>
<p><strong>获奖证书:</strong> <%= @teacher.award_certificates %></p>
<p><strong>荣誉:</strong> <%= @teacher.honors %></p>
<p><strong>教师证号:</strong> <%= @teacher.teacher_license %></p>
<p><strong>个人简介:</strong> <%= @teacher.bio %></p>
<p><strong>工作经验:</strong> <%= @teacher.experience %></p>
<p><strong>电话:</strong> <%= @teacher.phone %></p>
<p><strong>微信:</strong> <%= @teacher.wechat %></p>
<p><strong>学校:</strong> <%= @teacher.school.school_name if @teacher.school %></p>
<p><strong>专业:</strong> <%= @teacher.major.major_name if @teacher.major %></p>
<p><strong>学历:</strong> <%= @teacher.education.education_name if @teacher.education %></p>

<%= link_to "编辑", edit_admin_teacher_path(@teacher) %> |
<%= link_to "返回列表", admin_teachers_path %>