config/routes.rb
Rails.application.routes.draw do
  get "home/index"
  namespace :front do
    resources :majors
    resources :teachers
  end

  namespace :admin do
    get "/", to: "dashboards#index", as: :index
    resources :teachers
    resources :educations
    resources :majors
    resources :schools
    resources :users
  end
  devise_for :users

  get "up" => "rails/health#show", as: :rails_health_check

  root "homes#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/education.rb
class Education < ApplicationRecord
  validates :education_name, presence: { message: "学历名称必须填写" },
            uniqueness: { message: "学历已存在，请勿重复" }
end

app/models/major.rb
class Major < ApplicationRecord
  has_many :teachers
  validates :major_name, presence: true, uniqueness: true
end

app/models/school.rb
class School < ApplicationRecord
  validates :school_name, presence: true, uniqueness: true
end

app/models/teacher.rb
class Teacher < ApplicationRecord
  belongs_to :school
  belongs_to :major
  belongs_to :education
  has_one_attached :photo
end

app/models/user.rb
class User < ApplicationRecord
  attr_accessor :login

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         authentication_keys: [ :login ]

  validates :username, presence: true, uniqueness: true
  validates :phone, presence: true, uniqueness: true

  def self.find_for_database_authentication(warden_conditions)
    conditions = warden_conditions.dup
    login = conditions.delete(:login)&.downcase

    where(conditions).where(
    # ["lower(username) = :value OR lower(email) = :value", { value: login }]
    [ "lower(phone) = :value", { value: login } ]
    ).first
  end
end

app/controllers/admin/educations_controller.rb
class Admin::EducationsController < ApplicationController
  def index
    @educations = Education.all
  end

  def show
    @education = Education.find(params[:id])
  end

  def new
    @education = Education.new
  end

  def create
    @education = Education.new(education_params)
    if @education.save
      redirect_to admin_educations_path, notice: "成功创建学历类型"
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @education = Education.find(params[:id])
  end

  def update
    @education = Education.find(params[:id])
    if @education.update(education_params)
      redirect_to admin_education_path(@education), notice: "成功修改学历类型"
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @education = Education.find(params[:id])
    @education.destroy
    redirect_to admin_educations_path, notice: "成功删除学历类型"
  end

  private

  def education_params
    params.require(:education).permit(:education_name)
  end
end

app/controllers/admin/majors_controller.rb
class Admin::MajorsController < ApplicationController
  def index
    @majors = Major.all
  end

  def show
    @major = Major.find(params[:id])
  end

  def new
    @major = Major.new
  end

  def create
    @major = Major.new(majors_params)
    if @major.save
      redirect_to admin_majors_path, notice: "成功创建专业"
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @major = Major.find(params[:id])
  end

  def update
    @major = Major.find(params[:id])
    if @major.update(majors_params)
      redirect_to admin_major_path(@major), notice: "成功修改专业"
    else
      render :show, status: :unprocessable_entity
    end
  end

  def destroy
    @major = Major.find(params[:id])
    @major.destroy
    redirect_to admin_majors_path, notice: "成功删除专业"
  end

  private

  def majors_params
    params.require(:major).permit(:major_name)
  end
end

app/controllers/admin/schools_controller.rb
class Admin::SchoolsController < ApplicationController
  def index
    @schools = School.all
  end

  def show
    @school = School.find(params[:id])
  end

  def new
    @school = School.new
  end

  def create
    @school = School.new(school_params)
    if @school.save
      redirect_to admin_schools_path, notice: "添加学校 #{@school.school_name} 成功"
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @school = School.find(params[:id])
  end

  def update
    @school = School.find(params[:id])
    if @school.update(school_params)
      redirect_to admin_school_path(@school)
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @school = School.find(params[:id])
    @school.destroy
    redirect_to admin_schools_path, notice: "成功删除学校"
  end

  private

  def school_params
    params.require(:school).permit(:school_name, :address)
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :require_superuser
  before_action :set_user, only: [ :edit, :update, :destroy ]

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to admin_users_path, notice: "用户创建成功"
    else
      render :new
    end
  end

  def edit; end

  def update
    if @user.update(user_params)
      redirect_to admin_users_path, notice: "用户更新成功"
    else
      render :edit
    end
  end

  def destroy
    @user.destroy
    redirect_to admin_users_path, notice: "用户已删除"
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:username, :phone, :email, :password, :password_confirmation, :is_superuser)
  end

  def require_superuser
    redirect_to root_path, alert: "没有权限" unless current_user&.is_superuser?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  private

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_in, keys: [ :login ])
    # 注册时允许 username
    devise_parameter_sanitizer.permit(:sign_up, keys: [ :username, :email, :phone ])
    # 修改资料时允许 username
    devise_parameter_sanitizer.permit(:account_update, keys: [ :username, :email, :phone ])
  end
end

app/controllers/front/majors_controller.rb
class Front::MajorsController < ApplicationController
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def index
    @majors = Major.all
  end
end

app/helpers/admin/dashboards_helper.rb
module Admin::DashboardsHelper
end

app/helpers/admin/educations_helper.rb
module Admin::EducationsHelper
end

app/helpers/admin/majors_helper.rb
module Admin::MajorsHelper
end

app/helpers/admin/schools_helper.rb
module Admin::SchoolsHelper
end

app/helpers/admin/teachers_helper.rb
module Admin::TeachersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/front/majors_helper.rb
module Front::MajorsHelper
end

app/helpers/front/teachers_helper.rb
module Front::TeachersHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/educations/_form.html.erb
<!-- app/views/educations/_form.html.erb -->

<%= render 'shared/admin_navbar' %>

<% if education.errors.any? %>
  <ul>
    <% education.errors.messages.each do |_fields, messages| %>
      <% messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    <% end %>
  </ul>
<% end %>

<%= form_with model: [:admin, @education], local: true do |f| %>
  <div>
    <%= f.label :education_name, "学历名称" %><br>
    <%= f.text_field :education_name %>
  </div>

  <div>
    <%= f.submit education.new_record? ? "添加学历" : "更新学历" %>
  </div>
<% end %>

app/views/admin/educations/edit.html.erb
<h1>编辑学历</h1>
<%= render 'shared/admin_navbar' %>

<%= render "form", education: @education %>

<%= link_to "返回列表", admin_educations_path %>

app/views/admin/educations/index.html.erb
<h1>学历列表</h1>
<%= render "shared/admin_navbar" %>
<% if notice %>
  <p style="color: green;"><%= notice %></p>
<% end %>

<table>
  <thead>
  <tr>
    <th>ID</th>
    <th>学历名称</th>
    <th>操作</th>
  </tr>
  </thead>
  <tbody>
  <% @educations.each do |education| %>
    <tr>
      <td><%= education.id %></td>
      <td><%= education.education_name %></td>
      <td style="display: flex">
        <%= link_to "查看", admin_education_path(education) %> |
        <%= link_to "编辑", edit_admin_education_path(education) %> |
        <%= button_to "删除", admin_education_path(education), style: "cursor: pointer", method: :delete, data: { turbo_confirm: "确定删除吗？" } %>
      </td>
    </tr>
  <% end %>
  </tbody>
</table>

<br>

<%= link_to "添加新学历", new_admin_education_path %>

app/views/admin/educations/new.html.erb
<h1>添加新学历</h1>

<%= render "form", education: @education %>

<%= link_to "返回列表", admin_educations_path %>

app/views/admin/educations/show.html.erb
<h1>学历详情</h1>
<% if notice %>
  <p style="color: green;"><%= notice %></p>
<% end %>
<p>
  <strong>ID:</strong>
  <%= @education.id %>
</p>

<p>
  <strong>学历名称:</strong>
  <%= @education.education_name %>
</p>

<%= link_to "编辑", admin_education_path(@education) %> |
<%= link_to "返回列表", admin_educations_path %>